version: "3.8"
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest-Playground-Dev
      POSTGRES_DB: nest
    networks:
      - playground
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nest-Playground-Test
      POSTGRES_DB: nest
    networks:
      - playground
networks:
  playground:
